---
output: github_document
---

# Contributing to MOrepo

All researchers are welcome to contribute to MOrepo with instances, results etc. Each contribution
will be added as a sub-repository to the [MCDMSociety](https://github.com/MCDMSociety) organization
at GitHub. Name the repository MO-repo-`<first_author><year>` e.g. `MOrepo-Gadegaard16`.

As maintainers of MOrepo we will do our best to help you in the process. That is, you are always
welcome to contact us if you have problems following the steps below. The best way to do this is to
file an [issue](https://github.com/MCDMSociety/MOrepo/issues) at GitHub and we will try to resolve
your issues asap.


## Step 1 - Download the template repository

We have created a [template repository](https://github.com/MCDMSociety/MOrepo-Template) which have a
specific file structure. You can download the repository as a zip file and afterwards start
modifying/adding files.

The structure of an contribution folder is as follows:

- If you contribute with new instances, an `instances` folder (see 
  [Step2](#step-2---adding-test-instances-to-morepo)).
- If you contribute with results, a `results` folder (see [Step 3](step-3---adding-results-to-morepo).
- A file `citation.bib` containing the citation details for the study in BibTeX format. The study
  could e.g. be a paper where the instances have been used or the results calculated. We do not 
  recommend to add instances before you at least have written a report/note where the instances have been used. 
- A file `ReadMe.md` containing a presentation of the contribution. It must be written in 
  [markdown](https://en.wikipedia.org/wiki/Markdown) which is just a plain text format.
- A file `meta.json` in [json format](https://en.wikipedia.org/wiki/JSON) with details about the 
  contribution. For instance: 

```
{
   "contributionName": "Pedersen08",
   "maintainer" : "Lars Relund <junk@relund.dk>",
   "instanceGroups": [
      {
         "subfolder": "AP",
         "class": "Assignment",
         "objectives": 2,
         "tags": [ "ap", "assignmentProblem", "bi-AP"],
         "format": [ "xml" ],
         "desc": "Instances for the bi-objective assignment problem.",
         "creator" : "Lars Relund <junk@relund.dk>"
      },
      {
         "subfolder": "MMAP",
         "class": "Assignment",
         "objectives": 2,
         "tags": [ "bi-MMAP", "MMAP", "multi-modal" ],
         "format": [ "xml" ],
         "desc": "Instances for the bi-objective multi-modal assignment problem.",
         "creator" : "Lars Relund <junk@relund.dk>"
      }
   ]
}
```

The file contains 

   - `contributionName` (required): The name of the the contribution (string). We recommend to use the first author of the study and year.
   - `maintainer` (required): Name and e-mail of the maintainer of the sub-repository at GitHub (string).
   - `rawDesc` (optional): Short description of the raw format (string).
   - `algorithm` (optional): URL to the source code of the algorithm used in the study (string). It may be placed in this repository or somewhere else. 
   - `instanceGroups` (required - if new instances): An array with entries containing info about each group of instances (normally one entry for each sub-folder). Each entry contains
      * `subfolder` (required): Sub-folder of an instance format folder (if none set it to an empty string '').
      * `class` (required): Problem class (string). Have a look at the current problem classes ???. If your instances don't fit here add a new one. 
      * `objectives` (required): Number of objectives (number). 
      * `tags` (optional): An array with tags (use camel notation, not underscores).
      * `format` (required): Array with file formats. The names must be equal the instance format folders, e.g. if have a raw and xml format then the `instances` folder must have two sub-folders named `raw` and `xml`.
      * `creator` (required): Name and e-mail of the creator of the instances (string). Normally, the authors of the study.
      * `desc` (required): Description of the instance group (string).




## Step 2 - Adding test instances to MOrepo

If your study contains new test instances they should be added to the `instances` folder (remove it if you don't have any new instances). Instances are created for each study (paper/report/note) where the instances had been generated. Hence, if your study test instances used in previous multi-objective studies that not yet are a part of MOrepo, then kindly ask the authors of the previous study if you can include them in MOrepo (in a separate sub-repository). For instance if your study Gadegaard et. al. 2016 use instances from Nielsen et. al. 2014. Then create two contributions `MOrepo-Gadegaard16` (if new instances) and `MOrepo-Nielsen14` (with the old instances). As a result duplicated instance sets will not be generated.

The structure of the `instances` folder is as follows:

- A file `ReadMe.md` containing a description of the instances and formats (markdown). You may 
  browse the [sub-repositories](https://github.com/MCDMSociety) for examples. 
- A folder for each file format (e.g. `raw` and `xml`). That is, different file formats may be used. 
  If you have used a plain text/raw format then name this format `raw` and add a description to the 
  `ReadMe.md` file. Each file format folder contains the sub-folders defined in the `instanceGroups` 
  entry of the `meta.json` file. That is, if we consider the `meta.json` file above then folders 
  `AP` and `MMAP`.
- Instance file names must start with the contribution name and end with the file format suffix. 

The `instances` folder should not contain any compressed files.




## Step 3 - Adding results to MOrepo

Results of applying an algorithm to the test instances at MOrepo can be added to your contribution. 
If your study contains results they should be added to the `results` folder (remove it if you don't
have any results). For the moment only solutions in the objective space (e.g. the nondominated set)
can be stored. Results must be saved in json format with file name
`<instance_name>_result_<number>.json` where `<number>` is optional (`<number>` may be useful if
want to store different approximations of the nondominated set). `<instance_name>` must be equal to
the full instance name used at MOrepo (not including the file extension). The result file has the
following structure:

- `instanceName` (required): Name of instance not including the file extension (string).
- `contributionName` (required): The name of the the contribution (string).
- `objectives` (required): Number of objectives (number). 
- `objectiveType` (required): Array with strings `int`, `float` or `null` (unknown) giving the 
   numeric types of the objectives. Must have the same length as the number of objectives (array, null).
- `direction` (required): Array with strings `min` or `max` giving the direction of the objectives. 
   Must have the same length as the number of objectives (array).
- `comments` (optional): Misc comments about the results (string).
- `optimal` (required): `true` if an exact optimal solution, `false` is know an approximation, `null` 
   if unknown, i.e. may be optimal (boolean, null).
- `suppCard` (optional): Number of supported nondominated points (number). This is with respect to 
   the solution found. 
- `extCard` (optional): Number of extreme supported nondominated points (number)
- `card` (required): Number of points
- `points` (required): Array with nondominated points objects (array). Each point object consists of  
   `{"z1":1,"z2":4,"type":"se"}` with the objective values (i.e. extend to `z3` if three objectives)
   and type which may be either `us` (unsupported), `se` (supported extreme), `s` (supported - may 
   be extreme or nonextreme), `sne` (supported nonextreme), `null` (unknown). The type entry 

   
 (eller måske pointsClass i stedet for?)
optimal: (true, false, null)




## Step 4 - Adding other stuff


## Step 5 - Checking and submitting your contribution

When your contribution is ready, we recormmend to check if it is valid using the `MOrepoTools` R
package. Install [R](https://cran.r-project.org/index.html) and run:

```{r, eval=FALSE}
library(MOrepoTools)  # if not installed see the check.R file
checkContribution()
```

Remark: It may be easier if you also download [RStudio](https://www.rstudio.com/products/rstudio/)
and rename the file `MOrepo-Template.Rproj` to `MOrepo-<contributionName>.Rproj`. You now just open
this project file in RStudio and run the above code.

When you contribution is okay inform Lars Relund Nielsen <larsrn@econ.au.dk>. He will create the
sub-repository at GitHub and inform you (you may also do this before Step 1, if you would like to
work with git from the start). You can then add the files to git and GitHub using git from the
commandline inside the contribution folder:

```
git init
git add --all
git commit -am "First commit"
git remote add origin https://github.com/MCDMSociety/MOrepo-<contributionName>.git
git push -u origin master
```

Remark: If you use [RStudio](https://www.rstudio.com/products/rstudio/) go to `Tools -> Project
Options -> Git/SVN` and type in `https://github.com/MCDMSociety/MOrepo-<contributionName>.git`. You
can now do all git stuff from within RStudio.










